### ISSUE TITLE
Cmake file found & not found at the same time

### ISSUE THREAD

**Issue by realgs** [jahuth/virtualretina#4]
Hello,
after facing many problems installing your package I started with a fresh installation of Ubuntu 16.04.
I installed packages libxml2-dev and libx11-dev. Placed the retina folder into ~/ folder and run the bash script. I got the error in line 159 and 191 of the bash script. In the line 159 I read 
"# modify the prefix to change installation dir (default /usr/local)" and so I changed the folder to /usr/local and run the bash script again. Got the same error. It is kind of weird because first the script outputs that the cmake file has been found and then it throws two errors of 'No such file or directory' for the **SAME** file.

The output:

Looking for CMAKE (standard compilation tool)
----------------------------------------
**Found CMAKE executable:** /usr/local/virtualretina-master/External_Libraries/cmake-2.6.4-Linux-i386/bin/cmake
----------------------------------------
Installing CIMG (image processing library) locally
----------------------------------------
Found CIMG rootdir: External_Libraries/CImg-git
----------------------------------------
Installing MVASPIKE (spiking network library) locally
----------------------------------------
Found MVASPIKE rootdir: External_Libraries/mvaspike-1.0.18
Found MVASPIKE library: External_Libraries/mvaspike-1.0.18/lib/libmvaspike.so
----------------------------------------
Installing xmlParameters++ locally (with CMake)
----------------------------------------
Entering External_Libraries/xmlParameters++-1.1.1
download_build_all.bash: line 159: /usr/local/virtualretina-master/External_Libraries/cmake-2.6.4-Linux-i386/bin/cmake: **No such file or directory**
----------------------------------------
Compiling and installing VirtualRetina (with CMake)
----------------------------------------
download_build_all.bash: line 191: /usr/local/virtualretina-master/External_Libraries/cmake-2.6.4-Linux-i386/bin/cmake: **No such file or directory**

**Comment by jahuth** [comment]
Hello!

As a first disclaimer: the software is from 2008 and this repository only adds a few bug fixes. That being said, I will be happy to try to help you fix the install script so that it works for you.

There should be no need to move the package to `/usr/local`.
The `CMAKE_INSTALL_PREFIX:PATH` variable should be set to `"."` for all invocations of `cmake` since the script changes the current directory accordingly.
That particular comment is confusing and is intended for debugging more than for the user, so I will remove it.

In your case, you chose to download and install `cmake` locally through the install script when you executed it the first time, is that correct?
Can you verify whether or not any files exist at `"/usr/local/virtualretina-master/External_Libraries/cmake-2.6.4-Linux-i386/bin/cmake"`?
It is possible that the cmake installation (which just downloads and extracts a tar.gz archive) failed for you or that that version of cmake does not work for you.

A workaround is to install `cmake` through your package manager:

```
sudo apt-get install cmake
```

but I would prefer to know what is going wrong when you use the install script.

Some other points:

 * make sure to invoke the install command using `bash` (I think you did that or you would get a different error)
 * It is possible that a fresh ubuntu installation is missing some dev packages (eg. for the xml package), if you get an error that some header files are missing, please let me know!

It will help me a lot if you could look for the `cmake` files and maybe start the installation again in a fresh directory and send me the output of the first try to run the install script.

Thanks and let me know what you find!
Jacob

**Comment by realgs** [comment]
Yes I selected to install cmake locally. I chose it to be sure that the cmake version is compatible.

The file "/usr/local/virtualretina-master/External_Libraries/cmake-2.6.4-Linux-i386/bin/cmake" as well as "~/virtualretina-master/External_Libraries/cmake-2.6.4-Linux-i386/bin/cmake" exist.

Of course I run the installation script using bash command.

After installing cmake using apt-get and running bash in a fresh directory I get the following(full output attached as a file):

-- Configuring done
-- Generating done
-- Build files have been written to: /home/matt/virtualretina-master/VirtualRetina
Scanning dependencies of target virtualretina
[  2%] Building CXX object src/CMakeFiles/virtualretina.dir/basemapfilter.cc.o
[  4%] Building CXX object src/CMakeFiles/virtualretina.dir/baserecfilter.cc.o
[  6%] Building CXX object src/CMakeFiles/virtualretina.dir/basespikingchannel.cc.o
In file included from /home/matt/virtualretina-master/VirtualRetina/ext-lib-links/xmlParameters++/include/xmlparameters++/xmlparameters.h:330:0,
                 from /home/matt/virtualretina-master/VirtualRetina/src/radialscheme.h:5,
                 from /home/matt/virtualretina-master/VirtualRetina/src/basespikingchannel.h:6,
                 from /home/matt/virtualretina-master/VirtualRetina/src/basespikingchannel.cc:2:
/home/matt/virtualretina-master/VirtualRetina/ext-lib-links/xmlParameters++/include/xmlparameters++/xmlparameters_template_code.h:163:85: error: redeclaration of ‘template<class XMLIZED, class XMLIZED_b> void xmlParam::add_init(XMLIZED&, void (XMLIZED_b::*)(), bool)’ may not have default arguments [-fpermissive]
 void add_init (XMLIZED & object, void (XMLIZED_b::*func)(), bool afterChildren=false)
                                                                                     ^
/home/matt/virtualretina-master/VirtualRetina/ext-lib-links/xmlParameters++/include/xmlparameters++/xmlparameters_template_code.h:170:112: error: redeclaration of ‘template<class XMLIZED, class XMLIZED_b, class ARGCLASS> void xmlParam::add_init(XMLIZED&, void (XMLIZED_b::*)(ARGCLASS), ARGCLASS, bool)’ may not have default arguments [-fpermissive]
 void add_init (XMLIZED & object, void (XMLIZED_b::*func)(ARGCLASS), ARGCLASS argument, bool afterChildren=false)
                                                                                                                ^
src/CMakeFiles/virtualretina.dir/build.make:110: recipe for target 'src/CMakeFiles/virtualretina.dir/basespikingchannel.cc.o' failed
make[2]: *** [src/CMakeFiles/virtualretina.dir/basespikingchannel.cc.o] Error 1
CMakeFiles/Makefile2:90: recipe for target 'src/CMakeFiles/virtualretina.dir/all' failed
make[1]: *** [src/CMakeFiles/virtualretina.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

[output.txt](https://github.com/jahuth/virtualretina/files/1025188/output.txt)

**Comment by jahuth** [comment]
Thank you for your effort!
Your output looks good, I am glad that all the dependencies installed without problems.

The bug that makes your build fail was previously found by [another user](https://github.com/jahuth/virtualretina/issues/1#issuecomment-301458371). It has to do with the compiler version (that is why I have trouble fixing it since I can not replicate it on my machine).
I thought I fixed it, but did not change the same code in other header files at a different place.
So now I fixed it there as well. It would be great if you could pull and try to compile again.

Thanks!
Jacob

**Comment by realgs** [comment]
Hello again,
many thanks for your feedback! I pulled the repository and made a clean install in a new directory. The installation went well. I attach you the output as a file. There still is a problem with policy not being set but I suppose this is a minor issue. 
[output.txt](https://github.com/jahuth/virtualretina/files/1025726/output.txt)
I think it would be good to include such hints as an instruction for future users:
    Clear install of Ubuntu 16.04
    Install libxml2-dev and libx11-dev through your package manager.
    Install cmake: sudo apt-get install cmake
    copy the package to the directory of your choice and go to that directory
    conduct an automatic installation by typing bash download_build_all.bash
However, I think that now, after fixing some bugs in the code it will be much easier for other people to install the repository.
I'll keep you updated with the progress of our work related to your project.
Thanks!

**Comment by jahuth** [comment]
Very good!
Those are important hints, I will include them in the instructions!
Thank you for your persistence!
Jacob
